# -*- coding: utf-8 -*-
"""single image data augmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vPUqb4g-QWdAn0Jp9ulRj6gp37XDSxm_
"""

from keras.preprocessing import image
from keras.preprocessing.image import ImageDataGenerator

img=image.load_img('/content/dog.jpg',target_size=(200,200))

import matplotlib.pyplot as plt

plt.imshow(img)

img

type(img)

datagen=ImageDataGenerator(
    rotation_range=30,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    width_shift_range=0.2,
    height_shift_range=0.2
)

img=image.img_to_array(img)

type(img)

img.shape

input_batch=img.reshape(1,200,200,3)

i=0
for output in datagen.flow(input_batch,batch_size=1,save_to_dir='/content/aug'):
  i+=1
  if i==10:
    break